package com.shinway.mybatis.dto;

public class Terms {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terms.id
     *
     * @mbggenerated Mon Jun 27 18:34:26 ICT 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terms.name
     *
     * @mbggenerated Mon Jun 27 18:34:26 ICT 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terms.slug
     *
     * @mbggenerated Mon Jun 27 18:34:26 ICT 2016
     */
    private String slug;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terms.id
     *
     * @return the value of terms.id
     *
     * @mbggenerated Mon Jun 27 18:34:26 ICT 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terms.id
     *
     * @param id the value for terms.id
     *
     * @mbggenerated Mon Jun 27 18:34:26 ICT 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terms.name
     *
     * @return the value of terms.name
     *
     * @mbggenerated Mon Jun 27 18:34:26 ICT 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terms.name
     *
     * @param name the value for terms.name
     *
     * @mbggenerated Mon Jun 27 18:34:26 ICT 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terms.slug
     *
     * @return the value of terms.slug
     *
     * @mbggenerated Mon Jun 27 18:34:26 ICT 2016
     */
    public String getSlug() {
        return slug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terms.slug
     *
     * @param slug the value for terms.slug
     *
     * @mbggenerated Mon Jun 27 18:34:26 ICT 2016
     */
    public void setSlug(String slug) {
        this.slug = slug;
    }
}