package com.shinway.mybatis.dao;

import com.shinway.mybatis.dto.Terms;
import com.shinway.mybatis.dto.TermsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TermsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terms
     *
     * @mbggenerated Mon Jun 27 18:34:26 ICT 2016
     */
    int countByExample(TermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terms
     *
     * @mbggenerated Mon Jun 27 18:34:26 ICT 2016
     */
    int deleteByExample(TermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terms
     *
     * @mbggenerated Mon Jun 27 18:34:26 ICT 2016
     */
    int insert(Terms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terms
     *
     * @mbggenerated Mon Jun 27 18:34:26 ICT 2016
     */
    int insertSelective(Terms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terms
     *
     * @mbggenerated Mon Jun 27 18:34:26 ICT 2016
     */
    List<Terms> selectByExample(TermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terms
     *
     * @mbggenerated Mon Jun 27 18:34:26 ICT 2016
     */
    int updateByExampleSelective(@Param("record") Terms record, @Param("example") TermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terms
     *
     * @mbggenerated Mon Jun 27 18:34:26 ICT 2016
     */
    int updateByExample(@Param("record") Terms record, @Param("example") TermsExample example);
}